export const User = (
  username = "",
  email = "",
  password = "",
  is_artist = false,
  biography = "",
  availability = "unavailable",
  subscription = "standard",
  collections = [],
  subscriptions = [],
  subscribers = [],
  subscribersCount = 0,
  likedPublications = [],
  canPostArticles = true,
  fcmToken = "",
  profilePicture = "uploads/static/default-profile-pic.png",
  bannerPicture = "uploads/static/default-banner-pic.png",
  stripeAccountId = ""
)
